### ISSUE TITLE
Mushroom crashes game, error goes off-screen

### ISSUE THREAD

**Issue by qixils** [TurtleP/Portal-Bros#2]
Screenshot:
![image](https://cloud.githubusercontent.com/assets/13265322/19406978/10691716-9261-11e6-92b9-d71826520b25.png)

**Comment by TurtleP** [comment]
The first is since it's trying to set the image and quads to the big Mario no gun animation and the `portalGun` boolean is true, so it tries to index a nonexistent quad index. The latter is because of the game scroll.

**Comment by qixils** [comment]
Fixed as of latest update.
