### ISSUE TITLE
Mushrooms/1-ups don't go through portals

### ISSUE THREAD

**Issue by qixils** [TurtleP/Portal-Bros#4]
title explains it all. screenshot:
![image](https://cloud.githubusercontent.com/assets/13265322/19410685/728777c6-92c0-11e6-9243-3d8ffe8c314e.png)

**Comment by TurtleP** [comment]
Yeah, I'll do that. It's as simple as how I did it in Mario.lua or Goomba.lua in the event you want to do a pull request

**Comment by qixils** [comment]
I'll look into it
