### ISSUE TITLE
1-ups don't get removed after contact with Mario

### ISSUE THREAD

**Issue by qixils** [TurtleP/Portal-Bros#6]
infinite livess
![image](https://cloud.githubusercontent.com/assets/13265322/19410705/f0b7ce84-92c0-11e6-8433-ad083b32b8a2.png)
the 1-up is also on mario's head and doesn't fall through him but i'm going to assume that's working as intended

**Comment by TurtleP** [comment]
Oh. I forgot to loop through the powerups table. I should fix that. Haha.
